# Generated by Django 4.0.5 on 2023-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
