# Generated by Django 4.0.5 on 2023-04-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
    ]
