# Generated by Django 4.0.5 on 2023-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
