# Generated by Django 4.0.5 on 2023-04-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
