# Generated by Django 4.0.5 on 2023-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
